# Generated by Django 4.0.4 on 2022-10-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
